### ISSUE TITLE
Checking LocalStack CLI Fails

### ISSUE THREAD

**Issue by djallits** [localstack/cockpit#3]
With message: `Couldn't detect the LocalStack CLI. Make sure it is installed and on your path. See [documentation](https://docs.localstack.cloud/get-started/#localstack-cli) for more information.`

However, the `localstack-cli` is findable/usable within the terminal

```
➜ which localstack
/home/XXXXX/.local/bin/localstack
```

Sorry for the brevity of this report, but I did not see any means of gathering verbose logging from the app. Below are my system details.

Arch Linux 
Kernel: Linux 5.16.14-arch1-1 x86_64
Shell: zsh 5.8.1
Memory: 62.4 GiB
CPU: Intel® Core™ i9-10885H CPU @ 5.300GHz × 16
GPU: Intel CometLake-H GT2 [UHD Graphics]
GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
Disk Capacity: 2.0 TB
Desktop Environment: GNOME 41.3
Windowing System: Wayland

**Comment by kamil-bednarek** [comment]
Same here

**Comment by jackos** [comment]
I have the same issue, @djallits did you find a fix for this?

**Comment by jackos** [comment]
The problem here is that the program expects locales to be in `C.UTF8` and changing environment variables like:
```bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```
Won't help, as the Python application they've written must explicitly export the locale to be C.UTF-8 somewhere.

The problem with this is that some distro's don't have C.UTF-8 present and for distros like Arch Linux where we generate locales manually people don't usually include this one (it's not even one to uncomment in the default file)

To fix this on Arch or other systems with `locale-gen` do this:

1. Edit /etc/locale.gen and add this line:
```
C UTF-8
```
2. Run command:
```
locale-gen
```

Would be nice if the localstack developers could get the application to honor the environment variable:
```bash
export LANG=en_US.UTF-8
```
To fix this issue

**Comment by xPTM1219** [comment]
This problem is still happening in version 0.2.1 for Amazon Linux 2.

It appears that is looking for GLIB_2.29 but Amazon Linux 2 doesn't support more than GLIB_2.26.
I haven't tested this, but if a newer version of Amazon Linux is used (e.g Amazon Linux 2022) is possible that it will work.
This is mentioned in [repost.aws](https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2)

![image](https://github.com/localstack/cockpit/assets/22548244/f7800adc-a9d6-4082-a8c0-1f59e8e7aa29)

**Comment by djallits** [comment]
The definition of the issue provided by @jackos is accurate. His workaround works, but ultimately his recommendation to localstack should be considered.
