### ISSUE TITLE
I don't really see the point

### ISSUE THREAD

**Issue by Lewiscowles1986** [localstack/cockpit#4]
Hi, thanks for making localstack. Quite cool project!

The Cockpit, which I had to give out my email for... It doesn't really do anything. It looks like an ElectronJS app, but for how low-level it is. I might as well use a `docker-compose.yml` file.

On first start it complained a `~/.localstack` folder was not available. 

So I did `mkdir -p ~/.localstack`, and asked it to restart... The app did not restart.

Then once it did start it pulled `localstack` ignoring the `localstack-full` I had pulled.

Once it had pulled an image, it did not start it, or create a default profile.

Once the container was running, services was a reporting view, that gave no clear indication that I could change anything from that view. This was probably the most surprising thing.

So I created a profile (as it still had not)

Looks like environment var config. No autocompletes, no predetermined options. No blank UI states. No UI at all really.

I was just exploring. but I feel like maybe just focus on the docker side if this is working as intended.

From a business standpoint I was surprised there was no upselling of pro.

**Comment by MarcelStranak** [comment]
Hello @Lewiscowles1986,

I would like to thank you for your interest and your positive perception of LocalStack.

I understand that you did not have a good interaction with our additional tool, LocalStack Cockpit(Beta). I would like to apologize for the current state of the application. We are working on the improvements, and we are always interested in feedback from our customers. Nevertheless, I am thankful that you found the time and reported your insights, even though you had a poor experience using the application. We will go through your valid criticism and implement the necessary fixes and improvements.

Replying to the subject of this issue, I see that you are having doubts if this tool is even necessary. I would like to point that this tool, when fully released, will provide a simple way of working with LocalStack. You will not have to deal with any additional tools, (i.e., docker-compose) or any other external configurations to run your predefined LocalStack environment.

I hope you will continue providing us with your help in the future, and report to us any new problems or feature requirements that will be great to implement.

Thank you.

**Comment by Lewiscowles1986** [comment]
A high-level view of what I was thinking this was for based on:

> I would like to point that this tool, when fully released, will provide a simple way of working with LocalStack.

Why not have it embedded, controllable by environment variable to be on or off in the localstack container? From a brief spell I into how localstack is working the large container already has multiple services.

1. This could solve redeploy to change services
2. It’s like a point-of-sale for premium embedded in the thing most customers locally and in k8s are familiar with.
3. It should maybe know if it an reach whatever servers you use.
4. Work on re-config without redeploy
5. the ability to check the config (which you already must have to drive the UI in this app)
6. 

Thanks for taking the time and the more constructive feedback as it was intended. For now though I’m still lost as to the present day value. Maybe publish and link some content? Maybe you have a dev blog talking about the current feature set and why it exists to help people understand?

**Comment by thrau** [comment]
Thanks for the feedback Lewis @Lewiscowles1986!

> For now though I’m still lost as to the present day value.
To add to what Marcel was saying, we are exploring different ways to make it easier to control LocalStack. We have received feedback in the past that some users prefer working with a UI rather than having to rely on CLI tools like docker, docker-compose, or `localstack` to start, stop, and inspect LocalStack. The LocalStack Cockpit was one way for us to experiment with an integrated Desktop experience for LocalStack, at least an initial version to see whether people find this useful.

> Maybe you have a dev blog talking about the current feature set and why it exists to help people understand?
The dev blog is indeed something we are working on here: https://localstack.cloud/blog, there's also an entry for the cockpit, albeit maybe a bit brief.
There are also docs on the cockpit explaining the features and (hopefully) illustrating their usefulness: https://docs.localstack.cloud/get-started/cockpit/

I'll take the feedback to improve those things back to the team, and consider the issue resolved for now :-)
